### ISSUE TITLE
Pins should not be transparent

### ISSUE THREAD

**Issue by Chekote** [Medology/findalab#133]
## Problem:
The lab flash on the pins are transparent, which makes it hard to see clearly when multiple pins are stacked on top of each other:

<img width="183" alt="screen shot 2018-12-18 at 1 39 47 pm" src="https://user-images.githubusercontent.com/550486/50159194-014f3f00-02ce-11e9-8c97-134b1a4749c3.png">

## Acceptance Criteria
- [x] The lab flask icon should be white, not transparent
- [x] The background of the pin should still be transparent (around the circle)

**Comment by MeganPartida** [comment]
Tested this locally & it looks good 👍 
Updating ticket status from Pre-Production QA to **Deploy & Test**

**Comment by MeganPartida** [comment]
Verified this PR locally: https://github.com/Medology/stdcheck.com/pull/7581

The flask is still transparent.

Updating ticket status from pre-production QA to **In Progress**

**Comment by MeganPartida** [comment]
Verified PR #7581 and pr #822
the flasks are now filled in on both find a lab features.
Timothy assisted by removing the yarn cache because initially the flasks were still transparent.

Updating ticket status from Pre-Production QA to **Deploy & Test**

**Comment by MeganPartida** [comment]
Verified on production
On both STDcheck and HealthLabs the lab pins are not transparent and the flask is filled in with white

updating ticket status from Production QA to **Approval**
