### ISSUE TITLE
Step to assert # of pins returns double the visible amount

### ISSUE THREAD

**Issue by ramsey-medology** [Medology/findalab#137]
The previous method of obtaining the # of visible pins on the map was returning twice the # of visible icons. I believe it's due to the way google adds the pins for the default and selected icons. The generated elements are exactly alike. I resolved the failing test by accessing the underlying components, but this only asserts that they are created, not that they are actually on the DOM. We should investigate to see if there's a better way to assert this.

**Comment by Chekote** [comment]
@juanmrad the step finds double the pins that actually exist and then divides by two to determine how many are on the map. @ramsey-medology says that it's because there are two maps on the page.
