### ISSUE TITLE
Custom message in case error/not found

### ISSUE THREAD

**Issue by manuerumx** [Medology/findalab#143]
## Business Value:
[Want to read more on Types of Business Value?](https://docs.google.com/spreadsheets/d/1Bvcam238-mvESbTmEgLjkR0Dhrb9TmP4aQ7b3st8pMc/edit#gid=0)

Customer must know when the zip code he enter is not a valid one and receive a more specific message with the cause of error.

## Story:

**As a**  customer,
**I want** select a lab
**so that** i receive the correct message in case of error.

### Context
Zip code 20209 is not a valid US zip code even though it looks like one and we get a non-error response from the geocode services. In those scenarios FindALab returns a generic response.

```
Oops! Sorry, we could not find any testing centers near that location. Please check that the entered data is correct.
```

Instead, FindALab should allow to response custom messages from the projects that use it.

## Acceptance Criteria

In STDCheck the validation is already there but only when we try to geolocate the zipcode using the `GeoCodeController`.

Other sites use the `LabController` instead.

- [x] Point all the places where we are geolocating the zipcode first to the `GeoCodeController` to get the `lat` & `long` instead of `LabController`.

**Comment by fortoulrodolfo** [comment]
I will work on this one today. I should prob have a PR for each project that's pointing to LabController for geolocation.

**Comment by fortoulrodolfo** [comment]
I will address CR feedback. Ask for testing ideas for this.

**Comment by fortoulrodolfo** [comment]
Pairing with Donald today for testing suggestions.

**Comment by fortoulrodolfo** [comment]
Addressing CR feedback today.

**Comment by fortoulrodolfo** [comment]
Waiting for 3rd round of CR. It should move forward now.

**Comment by HLCharlie** [comment]
Waiting for QA feedback and will address as necessary today.

**Comment by fortoulrodolfo** [comment]
Waiting for QA feedback and will address as necessary today.

**Comment by splinfer** [comment]
## QA Local

Paired with @fortoulrodolfo to have some context, local tests were addressed using the zipcode in the sandbox, however we will see the real functionality in prod as it is easier to validate this.

Move to **D&T**

**Comment by fortoulrodolfo** [comment]
Scored with @aserv92 & @smijo149

**Comment by kabbatehl** [comment]
### QA Prod #1356
Verified the correct error message displays for invalid zip codes.  Moving to Approval.![screencapture-www-stdcheck-com-order-1590610155288](https://user-images.githubusercontent.com/62027147/83068917-b1ca8200-a02e-11ea-8080-30286a2d3472.png)
