### ISSUE TITLE
Lab title should be fully displayed

### ISSUE THREAD

**Issue by healthlabs-qa** [Medology/findalab#151]
## Describe the bug
Lab title is getting cut off in the lab results for findALab.

## To Reproduce
1. Go to 'findALab' in STDcheck.com
2. Search by `73053` in findALab.
3. Scroll down to 'Diagnostic Laboratory of' lab results

## Expected behavior
The whole lab title should be displayed. `Diagnostic Laboratory of Oklahoma`. It should allow max the double of size of that title.

## Actual behavior
The lab results are cutting of the lab title to `Diagnostic Laboratory of` instead of displaying the whole thing.

**Comment by rashidsaf** [comment]
Scored with @johnnie502 and @fortoulrodolfo

**Comment by juanmrad** [comment]
# QA - Pre  PR https://github.com/Medology/stdcheck.com/pull/9058

Tested on STDcheck creating labs with long titles and searching on findalab, they are properly displayed on the search.

When it comes to the pin map. they are too long and looks weird. I suggest to have a max width on this pin info box.

![Screen Shot 2019-11-14 at 6 33 58 PM](https://user-images.githubusercontent.com/5447733/68907665-36e2ef00-070e-11ea-8823-639789df87ff.png)


Moving back to in-progress

**Comment by MeganPartida** [comment]
for https://github.com/Medology/stdcheck.com/pull/9058 it was verified by Juan and is working as expected
for https://github.com/Medology/findalab/pull/152 it addresses the feedback Juan left in #9058 and can not be tested locally
- updating ticket to **deploy & test**

**Comment by MeganPartida** [comment]
## QA - Prod
- Verified that long lab titles are now shown properly on find a lab
![Screenshot from 2019-11-27 11-28-53](https://user-images.githubusercontent.com/45949961/69746100-303e7980-1109-11ea-9a0a-10d224cc3475.png)

- however, there are a lot of labs that have incomplete names in manage.  
Such as if you search for the zip code 73134, the second lab has a name of `diagnostic laboratory of` and if you look in manage, that name matches what is shown there. BUT the lab should be `diagnostic laboratory of oklahoma` 
so we may need to do some additional work to ensure all of the labs have correct names.
*This seems like it is out of scope though
- updating this ticket to **in progress** so Rashid can get feedback on next steps (whether to fix the incorrect names within this issue or open up a new ticket for those items)

**Comment by rashidsaf** [comment]
@MeganPartida 
This is a known issue, I talked with the @johnnie502. Once the Lab import feature is stable, we can import the correct Lab information.
 But as you mentioned, its not a part of the story

**Comment by MeganPartida** [comment]
Per the comment above, this is ready for approval!

**Comment by Chekote** [comment]
Still blocked. Cannot work on today.

**Comment by BKorenek** [comment]
Still blocked. Not working on today.

**Comment by Chekote** [comment]
Still blocked. Not working on today.

**Comment by Chekote** [comment]
Still blocked. Not working on today.

**Comment by BKorenek** [comment]
Still blocked. Not working on today.

**Comment by johnnie502** [comment]
Discussed with @juanmrad that we are going to close this bug since this is not going to be worked on in a foreseeable future, we will deal with it when it surfaced again.
