### ISSUE TITLE
Implement Dependabot

### ISSUE THREAD

**Issue by Chekote** [Medology/findalab#212]
# Description
Dependencies are not updated regularly on this project.

## Negative Impact:
Security, bug, and performance issues that are addressed with newer versions go unresolved.

## Proposed Solution:
Implement Dependabot on this project.

## How will the proposed solution address the negative impact(s)?
Dependabot will continually monitor the project and automatically open PRs for any available dependency updates.

## Side Effects
- Developers will need to review the PRs and ensure that everything is good
- Some updates will require changes to the code for compatibility, so someone will need to monitor for these and create issues as necessary.

## QA Needs
There should be no need to QA this. It does not affect the functionality of the project in any way. It purely configured a 3rd party tool (Dependabot) to monitor the repo and create pull requests when a dependency needs to be updated.

# Acceptance Criteria
- [ ] Dependabot is monitoring ALL supported dependencies on the project
- [ ] Dependabot is using the [new dependabot.yml file](https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates). NOT the [Dependabot web app dashboard](https://app.dependabot.com/accounts/Medology).

# Progress
### Ready for Planning
- [x] The Issue maintains standard format for Issues and meets INVEST
- [x] Description and Negative impact created
- [x] Initial Acceptance Criteria Defined
- [x] The person who will Approve story identified

### Ready for Ready to Work
- [ ] Acceptance Criteria Refined
- [ ] Issue size estimated by Dev Team
- [ ] Dependencies Identified

### Ready for Review
- [ ] Proposed solution, how it fixes the problem, and side effects defined and accepted by Approver
- [ ] Code implemented and built
- [ ] Testing implemented and passed

### Ready for Pre-Production QA
- [ ] Peer Reviews complete with all changes tested
- [ ] QA Needs defined
- [ ] Acceptance Test cases created and reviewed by QA
- [ ] Acceptance criteria met

### Ready for Deploy and Test
- [ ] PreProduction QA Test Passed
 
### Ready for Production QA
- [ ] Software deployed in production with no errors

### Ready for SM Approval
- [ ] Production QA Test Passed
- [ ] Manual Acceptance Test Results included in Comment

### Ready for PO Approval
- [ ] Issue complete and correct in all required sections
- [ ] All checkboxes checked

**Comment by Chekote** [comment]
Scored with @BKorenek and @aserv92

**Comment by kabbatehl** [comment]
### QA Local #210  
Nothing to test. Moving to deploy and test.

**Comment by Chekote** [comment]
Deploy & Test:

After merging, [Dependabot](https://app.dependabot.com/accounts/Medology) shows that the repo is successfully migrated to Github.

![Screen Shot 2020-07-16 at 1.47.59 PM.png](https://images.zenhubusercontent.com/57d18ae5e40e5714b16e8533/2542f53b-0a83-4d40-a329-e5436e553dbd)

**Comment by kabbatehl** [comment]
### QA Prod #210
Nothing to test. Moving to Approval.
