### ISSUE TITLE
Initial Set-up Findalab TypeScript

### ISSUE THREAD

**Issue by juanmrad** [Medology/findalab#244]
# Story
As a Developer I need Findalab to be a TypeScript library so it can be easily added and implemented to all our other new TypeScript projects.

## Business Value  
We will be able to keep using this library on its own as well as add appropriate testing and be able to test integration on other systems.

# Acceptance Criteria
- [x] Findalab TypeScript project is created.
- [x] Findalab project is initialized.
- [x] Features/functionality of current findalab is identified and issues to convert from current version to TypeScript are created.
 
# Subject Domain Experts
- Johnnie
- Juan

# Proposed Solution  
We create multiple issues for each feature/functionality that current findalab has to be implemented on TypeScript.
The project is initialized as a new branch that can be worked on so it does not interrupt current findalab.

# Progress
### Ready for Planning
- [x] The Issue maintains standard format for Issues and meets INVEST
- [x] Story and Business Value complete
- [x] Initial Acceptance Criteria Defined
- [x] The person who will Approve story identified

### Ready for Ready to Work
- [x] Acceptance Criteria Refined
- [x] Issue size estimated by Dev Team
- [x] Dependencies Identified

### Ready for Review
- [x] Proposed solution defined and accepted by Approver
- [x] Code implemented and built
- [x] Testing implemented and passed

### Ready for Pre-Production QA
- [x] Peer Reviews complete with all changes tested
- [x] All features implemented
- [x] All features not yet implemented or inactive are hidden from the user
- [x] Special testing instructions noted
- [x] Acceptance Test cases created and reviewed by QA
- [x] Acceptance criteria met

### Ready for Deploy and Test
- [x] PreProduction QA Test Passed
- [x] New production environmental variables added (if applicable)
 
### Ready for Production QA
- [x] Software deployed in production with no errors

### Ready for SM Approval
- [x] Production QA Test Passed
- [x] Manual Acceptance Test Results included in Comment

### Ready for PO Approval
- [x] Issue complete and correct in all required sections
- [x] All checkboxes checked

**Comment by johnnie502** [comment]
* Going to address the code review feedback today

**Comment by juanmrad** [comment]
# Pre-Prod QA:

Nothing to test.

**Comment by juanmrad** [comment]
@johnnie502 Please check the boxes if all has been completed.
