### ISSUE TITLE
Enable scheduled workflow

### ISSUE THREAD

**Issue by PayneWheat** [Medology/findalab#374]
# Story

## Short Summary
To ensure the health of this project, we should enable a [scheduled workflow](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow) for the `master` branch in CircleCI.

This repo is relatively stable and there is not a lot of PRs being merged, so running a nightly build may be overkill. Check with Johnnie about the frequency of the automated workflow.

## Acceptance Criteria
- [ ] A scheduled workflow has been enabled for this project

### Pros
* Provides insight on the health of a project, and makes it easier to diagnose IFT/CFTs.

### Cons
* Additional costs in CircleCI.

## Subject Matter Experts
Johnnie
Rodolfo

## Notes
[CircleCI documentation](https://circleci.com/docs/2.0/)

## Announcement Message
A [frequency] scheduled workflow has been enabled for findalab

**Comment by fortoulrodolfo** [comment]
Team Umami will take care of this implementation
